### PR TITLE
fix: No get-sli.finished event is sent if Dynatrace credentials cannot be found

### LINKED ISSUE #605: No `get-sli.finished` event is sent if Dynatrace credentials cannot be found
**Describe the bug**
Currently, if the dynatrace-service is unable to find Dynatrace credentials, it responds to Keptn Uniform with a `sh.keptn.log.error` event, however never sends a `get-sli.started` or `get-sli.finished` event. As a result, the sequence continues to run in the Keptn UI even though get-sli effectively failed in the back end.

This issue highlights a similar problem to #381, although it manifests in a different way.

**Versions**

Versions of the applicable components

* Dynatrace Service version :  0.18.1
* Dynatrace cluster version :
* Keptn version: 0.10.0

**To Reproduce**

1. I have a dynatrace.conf.yaml file configured like this:
version: '0.1.0'
dtCreds: dynatrace-prod
dashboard: query

2. There is no credentials with the name "dynatrace-prod" defined in Keptn. 
3. Then I run the evaluation.
The following error is thrown in the log:
`time="2021-11-22T15:00:34Z" level=error msg="Could not get dynatrace credentials and config" error="could not get credentials from secret \"dynatrace-prod\": secrets \"dynatrace-prod\" is forbidden: User \"system:serviceaccount:lyn50682:dynatrace-service\" cannot get resource \"secrets\" in API group \"\" in the namespace \"lyn50682\""`
4. go to Sequences page and take a look to the sequence which was started

Issue:
Here we see the sequence is started and it continues to run:
image
                 

**Expected behavior**
In this case the evaluation should be immediately failing in UI like presented in below img and of course presenting the correct and related error messages why the evaluation is failed:
image

**Screenshots**

**Additional context**
logs from dynatrace-service
```
time="2021-11-22T15:00:34Z" level=info msg="Found dynatrace/dynatrace.conf.yaml for service" project=dynatrace service=health stage=quality-gate
time="2021-11-22T15:00:34Z" level=error msg="Could not get dynatrace credentials and config" error="could not get credentials from secret \"dynatrace-prod\": secrets \"dynatrace-prod\" is forbidden: User \"system:serviceaccount:lyn50682:dynatrace-service\" cannot get resource \"secrets\" in API group \"\" in the namespace \"lyn50682\""
time="2021-11-22T15:00:34Z" level=error msg="Could not retrieve integration ID from Keptn Uniform" error="there are more than one integrations with name dynatrace-service - this is not supported"
time="2021-11-22T15:00:34Z" level=error msg="HandleEvent() returned an error" error="there are more than one integrations with name dynatrace-service - this is not supported"
time="2021-11-22T15:00:35Z" level=info msg="Found dynatrace/dynatrace.conf.yaml for stage" project=dynatrace stage=quality-gate
```

### PR DESCRIPTION
**Pull request by arthurpitman**
Closes #605

### CODE REVIEW

File: internal/event_handler/handler.go [hunk 1]
```diff
@@ -68,6 +69,7 @@ func NewEventHandler(event cloudevents.Event) DynatraceEventHandler {
 
 	dtConfigGetter := config.NewDynatraceConfigGetter(keptn.NewDefaultResourceClient())
 	dynatraceConfig, dynatraceCredentials, secretName, err := getDynatraceCredentialsAndConfig(keptnEvent, dtConfigGetter)
+	err = errors.New("Fake error")
```
Comment (j-poecher) [inline internal/event_handler/handler.go:72]: I guess this is a left-over

Comment (arthurpitman) [reply internal/event_handler/handler.go]: Yes! thank you!

**Review by j-poecher — APPROVED** [review]
lgtm
